### ISSUE TITLE
vidloop & sdl2 display fails

### ISSUE THREAD

**Issue by hargut** [alfredh/baresip#201]
Dear Alfred,

I've discovered a segfault with sdl2 & "-e/vidloop h264" on my test setup:
```
hargut@benchvice:~/baresip_alfredh/baresip$ LANG=C gdb --args ./baresip -e"/vidloop h264"   
GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./baresip...done.
(gdb) run
Starting program: /home/hargut/baresip_alfredh/baresip/baresip -e/vidloop\ h264
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
baresip v0.5.0 Copyright (C) 2010 - 2017 Alfred E. Heggestad et al.
Local network address:  IPv4=enp2s0:10.0.0.11 
aucodec: PCMU/8000/1
aucodec: PCMA/8000/1
aufilt: vumeter
avcodec: using h264 decoder by name (h264_cuvid)
vidcodec: H264
vidcodec: H263
vidcodec: MP4V-ES
avcodec: using h264 encoder by name (h264_nvenc)
vidsrc: avformat
vidisp: x11
vidisp: sdl2
medianat: stun
medianat: turn
medianat: ice
Populated 1 account
Populated 3 contacts
Populated 2 audio codecs
Populated 1 audio filter
Populated 3 video codecs
Populated 0 video filters
baresip is ready.
/vidloop h264
Enable video-loop on avformat,/home/hargut/dwhelper/st-pl.mp4: 1280 x 720
vidloop: avformat,/home/hargut/dwhelper/st-pl.mp4: open video source: 1280 x 720 at 500 fps
[New Thread 0x7fffd4e9a700 (LWP 12582)]
vidloop: open video display (sdl2.nil)
vidloop: enabled encoder H264 (500 fps, 1000000 bit/s)
vidloop: enabled decoder H264
avcodec: h264 encoder activated
avcodec: h264 decoder activated
[New Thread 0x7fffcffff700 (LWP 12586)]
[New Thread 0x7fffcf7fe700 (LWP 12588)]
[New Thread 0x7fffceffd700 (LWP 12590)]
[h264_cuvid @ 0x5555558caf60] Invalid pkt_timebase, passing timestamps as-is.
Enabled codec: H264
[New Thread 0x7fffcd7ca700 (LWP 12591)]
[New Thread 0x7fffccfc9700 (LWP 12592)]
reg: sip:hargut@home: Register: Destination address required
vidloop: codec decode: Bad message
vidloop: codec decode: Bad messagePS=0.0      0 kbit/s       
vidloop: codec decode: Bad message
vidloop: codec decode: Bad message

Thread 2 "baresip" received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffd4e9a700 (LWP 12582)]
0x00007fffd848a39e in display (st=0x5555558c7d40, title=0x7fffd4e9d26e "Video Loop", frame=0x7fffd4e99bf0) at modules/sdl2/sdl.c:177
177                     const unsigned stp = frame->linesize[0] / frame->linesize[i];
(gdb) bt
#0  0x00007fffd848a39e in display (st=0x5555558c7d40, title=0x7fffd4e9d26e "Video Loop", frame=0x7fffd4e99bf0) at modules/sdl2/sdl.c:177
#1  0x0000555555578251 in vidisp_display (st=0x5555558c7d40, title=0x7fffd4e9d26e "Video Loop", frame=0x7fffd4e99bf0) at src/vidisp.c:125
#2  0x00007fffd4e9c336 in display (vl=0x555555ba4ca0, frame=0x7fffd4e99bf0) at modules/vidloop/vidloop.c:112
#3  0x00007fffd4e9c567 in packet_handler (marker=true, hdr=0x7fffd4e99cc1 "a\351\324", hdr_len=1, 
    pld=0x5555559f646b "\340\202\277\251b$\016\240\335\003\272\352i[\266<W2\207\377\235\314v\253\204\325\356\027\207\t\a_4q?\264P\017\220\264\272\212#\341lB\261&\005\202v\002\231\003\206\314", pld_len=478, arg=0x555555ba4ca0) at modules/vidloop/vidloop.c:162
#4  0x00005555555751db in rtp_send_data (hdr=0x7fffd4e99cc1 "a\351\324", hdr_sz=1, 
    buf=0x5555559f646b "\340\202\277\251b$\016\240\335\003\272\352i[\266<W2\207\377\235\314v\253\204\325\356\027\207\t\a_4q?\264P\017\220\264\272\212#\341lB\261&\005\202v\002\231\003\206\314", sz=478, eof=true, pkth=0x7fffd4e9c3a3 <packet_handler>, arg=0x555555ba4ca0) at src/h264.c:109
#5  0x000055555557526d in h264_nal_send (first=true, last=true, marker=true, ihdr=97, 
    buf=0x5555559f646b "\340\202\277\251b$\016\240\335\003\272\352i[\266<W2\207\377\235\314v\253\204\325\356\027\207\t\a_4q?\264P\017\220\264\272\212#\341lB\261&\005\202v\002\231\003\206\314", size=478, maxsz=1480, pkth=0x7fffd4e9c3a3 <packet_handler>, arg=0x555555ba4ca0) at src/h264.c:122
#6  0x0000555555575467 in h264_packetize (buf=0x5555559f6460 "", len=489, pktsize=1480, pkth=0x7fffd4e9c3a3 <packet_handler>, arg=0x555555ba4ca0) at src/h264.c:172
#7  0x00007ffff5556f48 in encode (st=0x555555970120, update=false, frame=0x7fffd4e99e80) at modules/avcodec/encode.c:777
#8  0x00007fffd4e9c719 in vidsrc_frame_handler (frame=0x7fffd4e99e80, arg=0x555555ba4ca0) at modules/vidloop/vidloop.c:209
#9  0x00007fffea623558 in handle_packet (st=0x555555ba4eb0, pkt=0x7fffd4e99ef0) at modules/avformat/avformat.c:175
#10 0x00007fffea62367c in read_thread (data=0x555555ba4eb0) at modules/avformat/avformat.c:217
#11 0x00007ffff79546ca in start_thread (arg=0x7fffd4e9a700) at pthread_create.c:333
#12 0x00007ffff747f0af in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:105
(gdb) print frame->linesize[0]
$1 = 1280
(gdb) print frame->linesize[i] 
$2 = 0
(gdb) print i
$1 = 2
(gdb)
```

dmesg states:
```
[ 6018.549018] traps: baresip[12512] trap divide error ip:7fa06da5939e sp:7fa06a4689a0 error:0 in sdl2.so[7fa06da58000+2000]
```
Looks like a division by zero which could be related to getting an incomplete frame from the decoder.

Best regards,
Harald

**Comment by alfredh** [comment]
most likely related to https://github.com/alfredh/baresip/issues/202
as the incoming frames has only 2 planes.

**Comment by alfredh** [comment]
fixed in https://github.com/alfredh/baresip/commit/055e3dff56b39b973774605b49c787c03d6a6d78
